#!/bin/sh

# Kill all so can be restarted
killall -9 xfce4-power-manager polybar picom numlockx nitrogen unclutter;

# Kill all Tray Icons
killall -9 blueberry-tray nm-applet xfce4-clipman xfce4-notes;

# Start Hotkey Daemon
pidof sxhkd || sxhkd &

# XFCE4 Stuff ===================================================================

# Settings Daemon
pidof xfsettingsd || xfsettingsd &

# Notification Daemon
pidof /usr/lib/xfce4/notifyd/xfce4-notifyd || /usr/lib/xfce4/notifyd/xfce4-notifyd &

# Polkit
pidof /usr/lib/xfce-polkit/xfce-polkit || /usr/lib/xfce-polkit/xfce-polkit &

# Power Management
xfce4-power-manager &

# ===============================================================================

# Tray Icons ===================================================================

# Bluetooth
blueberry-tray &

# Network Manager
nm-applet &

# Clipboard Manager
#xfce4-clipman &

# Notes
#xfce4-notes &

# ===============================================================================

# Bluetooth OBEX Agent (Allows to receive files via Bluetooth)
/usr/lib/blueberry/blueberry-obex-agent.py &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Touchpad Gestures Support
/usr/bin/libinput-gestures &

# Bar
$HOME/.config/polybar/launch.sh --cuts-single &

# Compositor
picom &

# Numlock always on
numlockx &

# Wallpaper
nitrogen --restore &

# Auto hide mouse, this is not official unclutter, is unclutter-xfixes-git from the aur, that adds the touch support
unclutter --hide-on-touch &

# replace neovim colorscheme
sed -i "s/theme =.*$/theme = \"nord\",/g" $HOME/.config/nvim/lua/custom/chadrc.lua &

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal" &
cp "$XFCE_TERM_PATH"/colorschemes/nord "$XFCE_TERM_PATH"/terminalrc &

# change cava colorscheme
AVA_PATH="$HOME/.config/cava" &
cp "$CAVA_PATH"/colorschemes/nord "$CAVA_PATH"/config &
