#!/bin/sh

# Kill all so can be restarted
killall -9 xfce4-power-manager polybar picom numlockx nitrogen unclutter nm-applet

# Make sxhkd reload its configuration files
pkill -USR1 -x sxhkd

# Start Hotkey Daemon
pidof sxhkd || sxhkd &

# XFCE4 Settings Daemon
pidof xfsettingsd || xfsettingsd &

# Notification Daemon
pidof dunst || dunst -config $HOME/.config/i3/dunstrc &

# Polkit
pidof /usr/lib/xfce-polkit/xfce-polkit || /usr/lib/xfce-polkit/xfce-polkit &

# Power Management
xfce4-power-manager &

# Fix cursor
#xsetroot -cursor_name left_ptr &

# Bar
$HOME/.config/bspwm/polybar/launchbar.sh &

# Compositor
#xfwm4 &
picom --config $HOME/.config/bspwm/picom.conf &

# Numlock always on
numlockx &

# Wallpaper
nitrogen --restore &
#feh --bg-scale <path-to-wallpaper> &

# Auto hide mouse, this is not official unclutter, is unclutter-xfixes-git from the aur, that add the touch support
unclutter --hide-on-touch &

# Network Manager tray icon
nm-applet &

# Tabs support
#tabbed &

# replace neovim colorscheme
sed -i "s/theme =.*$/theme = \"nord\",/g" $HOME/.config/nvim/lua/custom/chadrc.lua &

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal" &
cp "$XFCE_TERM_PATH"/colorschemes/nord "$XFCE_TERM_PATH"/terminalrc &

# change cava colorscheme
AVA_PATH="$HOME/.config/cava" &
cp "$CAVA_PATH"/colorschemes/nord "$CAVA_PATH"/config &
