#! /bin/sh

# Include Autostart Script
source $(dirname $0)/autostart

#if  xrandr | grep "HDMI1 connected"; then
#	bspc monitor primary -d 1 2 3 4 5 6 7 8
#	bspc monitor HDMI1 -d 9 10
#else
#	bspc monitor primary -d 1 2 3 4 5 6 7 8 9 10
#fi

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

if test -z "$VNCDESKTOP" && test "$(exec bspc query -M | exec wc -l)" -gt 1; then
    bspc monitor primary -d 1 2 3 4 5
    bspc monitor ^2 -d 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config automatic_scheme            alternate
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       false

bspc config normal_border_color         "#2E3440"
# bspc config active_border_color         "#FF0000"
bspc config focused_border_color        "#81A1C1"
bspc config presel_feedback_color       "#BF616A"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Vlc border=off state=floating center=true
bspc rule -a Surf border=off state=floating center=true
bspc rule -a Xfce4-settings-manager border=off state=floating center=true
bspc rule -a deepin-calculator state=floating border=off center=true
bspc rule -a "Free Download Manager" state=floating border=off center=true
bspc rule -a Spotify desktop='^5' # Not working for Spotify

bspc config external_rules_command $(dirname $0)/external_rules
#bspc config external_rules_command $(dirname $0)/cleanfullscreen/cleanfullscreen
